### PR TITLE
Added workflows/test.yml + fixed tests

### PR DESCRIPTION
**Pull request by jbigman**
Hi @facundoolano, i made a github action similar to the play-store-scrapper one. This way it will be possible to merge other pull requests in the pipe.

This PR also contains fixes in tests

I currently removed the npm audit because this project uses the deprecated "request" library.

### CODE REVIEW

**Comment by jbigman** [comment]
You can take a look on action result on my fork : https://github.com/jbigman/app-store-scraper/actions

**Comment by jbigman** [comment]
up

**Review by facundoolano — APPROVED** [review]
Great, thanks for the contribution!

**Comment by facundoolano** [comment]
Not sure why this isn't triggering from the PR. I will merge to see if next one runs it.

**Comment by facundoolano** [comment]
If you have the bandwidth, could you send another one to remove the travis.yml file, and perhaps replacing the status badge in the README? (don't remember if github actions have badges, but otherwise removing the current one would ok as well)

**Pull request merged**
